import type {
  MediaItem,
  Episode,
  CalendarEntry,
  WatchSession,
  Notification,
  Stats,
  CustomList,
  MediaType,
} from "./types";

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
};
const daysFromNow = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
};
const hoursAgo = (n: number) => {
  const d = new Date(today);
  d.setHours(d.getHours() - n);
  return d.toISOString();
};

const ALL_GENRES = [
  "Action", "Adventure", "Animation", "Comedy", "Crime", "Documentary",
  "Drama", "Family", "Fantasy", "History", "Horror", "Music", "Mystery",
  "Romance", "Science Fiction", "Thriller", "War", "Western",
];

const ARABIC_GENRES = ["دراما", "كوميديا", "تشويق", "تاريخي", "اجتماعي", "رومانسي", "بوليسي"];

// Sample poster colors (we'll render as gradient placeholders)
const gradients = [
  "from-rose-500 to-orange-500",
  "from-purple-600 to-indigo-600",
  "from-emerald-500 to-teal-600",
  "from-amber-500 to-red-600",
  "from-cyan-500 to-blue-600",
  "from-pink-500 to-rose-600",
  "from-violet-600 to-purple-700",
  "from-lime-500 to-emerald-600",
];

const pickGradient = (seed: number) => gradients[seed % gradients.length];

// ─────────────────────────────────────────────────────────────
// TV Shows — 16 items across various statuses
// ─────────────────────────────────────────────────────────────

const tvShows: MediaItem[] = [
  {
    id: "tv-1",
    tmdbId: 94605,
    mediaType: "tv",
    title: "Arcane",
    posterPath: "/arcane.jpg",
    backdropPath: "/arcane-bg.jpg",
    overview: "Set in Utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions.",
    releaseDate: "2021-11-06",
    runtime: 45,
    genres: ["Animation", "Action", "Adventure", "Drama", "Science Fiction"],
    voteAverage: 8.7,
    voteCount: 5234,
    status: "watching",
    progress: 12,
    totalEpisodes: 18,
    currentSeason: 2,
    currentEpisode: 4,
    userRating: 92,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(120),
    lastWatchedAt: hoursAgo(6),
    nextEpisode: { season: 2, episode: 5, name: "Watch It All Burn", airDate: daysFromNow(3), runtime: 42 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 9, airDate: "2021-11-06" },
      { season: 2, name: "Season 2", episodeCount: 9, airDate: "2024-11-09" },
    ],
    providers: ["Netflix"],
  },
  {
    id: "tv-2",
    tmdbId: 1399,
    mediaType: "tv",
    title: "Game of Thrones",
    posterPath: "/got.jpg",
    backdropPath: "/got-bg.jpg",
    overview: "Seven noble families fight for control of the mythical land of Westeros.",
    releaseDate: "2011-04-17",
    runtime: 60,
    genres: ["Drama", "Adventure", "Fantasy", "Action"],
    voteAverage: 8.5,
    voteCount: 18534,
    status: "completed",
    progress: 73,
    totalEpisodes: 73,
    currentSeason: 8,
    currentEpisode: 6,
    userRating: 88,
    favorite: true,
    rewatchCount: 1,
    addedAt: daysAgo(800),
    lastWatchedAt: daysAgo(60),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 10, airDate: "2011-04-17" },
      { season: 2, name: "Season 2", episodeCount: 10, airDate: "2012-04-01" },
      { season: 3, name: "Season 3", episodeCount: 10, airDate: "2013-03-31" },
      { season: 4, name: "Season 4", episodeCount: 10, airDate: "2014-04-06" },
      { season: 5, name: "Season 5", episodeCount: 10, airDate: "2015-04-12" },
      { season: 6, name: "Season 6", episodeCount: 10, airDate: "2016-04-24" },
      { season: 7, name: "Season 7", episodeCount: 7, airDate: "2017-07-16" },
      { season: 8, name: "Season 8", episodeCount: 6, airDate: "2019-04-14" },
    ],
    providers: ["HBO Max"],
  },
  {
    id: "tv-3",
    tmdbId: 66732,
    mediaType: "tv",
    title: "Stranger Things",
    posterPath: "/st.jpg",
    backdropPath: "/st-bg.jpg",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments.",
    releaseDate: "2016-07-15",
    runtime: 55,
    genres: ["Drama", "Fantasy", "Horror", "Science Fiction", "Mystery"],
    voteAverage: 8.6,
    voteCount: 14233,
    status: "watching",
    progress: 25,
    totalEpisodes: 42,
    currentSeason: 4,
    currentEpisode: 9,
    userRating: 90,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(200),
    lastWatchedAt: daysAgo(14),
    nextEpisode: { season: 5, episode: 1, name: "The Crawl", airDate: daysFromNow(180), runtime: 60 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 8, airDate: "2016-07-15" },
      { season: 2, name: "Season 2", episodeCount: 9, airDate: "2017-10-27" },
      { season: 3, name: "Season 3", episodeCount: 8, airDate: "2019-07-04" },
      { season: 4, name: "Season 4", episodeCount: 9, airDate: "2022-05-27" },
    ],
    providers: ["Netflix"],
  },
  {
    id: "tv-4",
    tmdbId: 60625,
    mediaType: "tv",
    title: "Rick and Morty",
    posterPath: "/ram.jpg",
    backdropPath: "/ram-bg.jpg",
    overview: "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family.",
    releaseDate: "2013-12-02",
    runtime: 25,
    genres: ["Animation", "Comedy", "Science Fiction", "Adventure"],
    voteAverage: 8.3,
    voteCount: 9876,
    status: "on_hold",
    progress: 40,
    totalEpisodes: 71,
    currentSeason: 7,
    currentEpisode: 5,
    userRating: 85,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(400),
    lastWatchedAt: daysAgo(90),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 11, airDate: "2013-12-02" },
      { season: 2, name: "Season 2", episodeCount: 10, airDate: "2015-07-26" },
      { season: 3, name: "Season 3", episodeCount: 10, airDate: "2017-04-01" },
      { season: 4, name: "Season 4", episodeCount: 10, airDate: "2019-11-10" },
      { season: 5, name: "Season 5", episodeCount: 10, airDate: "2021-06-20" },
      { season: 6, name: "Season 6", episodeCount: 10, airDate: "2022-09-04" },
      { season: 7, name: "Season 7", episodeCount: 10, airDate: "2023-10-15" },
    ],
    providers: ["HBO Max"],
  },
  {
    id: "tv-5",
    tmdbId: 87108,
    mediaType: "tv",
    title: "Chernobyl",
    posterPath: "/chernobyl.jpg",
    backdropPath: "/chernobyl-bg.jpg",
    overview: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
    releaseDate: "2019-05-06",
    runtime: 60,
    genres: ["Drama", "History", "Thriller"],
    voteAverage: 8.7,
    voteCount: 6543,
    status: "completed",
    progress: 5,
    totalEpisodes: 5,
    currentSeason: 1,
    currentEpisode: 5,
    userRating: 95,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(150),
    lastWatchedAt: daysAgo(30),
    seasons: [{ season: 1, name: "Miniseries", episodeCount: 5, airDate: "2019-05-06" }],
    providers: ["HBO Max"],
  },
  {
    id: "tv-6",
    tmdbId: 71712,
    mediaType: "tv",
    title: "The Good Doctor",
    posterPath: "/gooddoctor.jpg",
    backdropPath: "/gooddoctor-bg.jpg",
    overview: "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital.",
    releaseDate: "2017-09-25",
    runtime: 45,
    genres: ["Drama"],
    voteAverage: 8.0,
    voteCount: 12344,
    status: "watchlist",
    progress: 0,
    totalEpisodes: 100,
    currentSeason: 1,
    currentEpisode: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(10),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 18, airDate: "2017-09-25" },
      { season: 2, name: "Season 2", episodeCount: 18, airDate: "2018-09-24" },
    ],
    providers: ["Hulu"],
  },
  {
    id: "tv-7",
    tmdbId: 62273,
    mediaType: "tv",
    title: "Better Call Saul",
    posterPath: "/bcs.jpg",
    backdropPath: "/bcs-bg.jpg",
    overview: "Six years before Saul Goodman meets Walter White, we meet him when the man who will become Saul Goodman is known as Jimmy McGill.",
    releaseDate: "2015-02-08",
    runtime: 45,
    genres: ["Drama", "Crime"],
    voteAverage: 8.5,
    voteCount: 5432,
    status: "watching",
    progress: 35,
    totalEpisodes: 63,
    currentSeason: 5,
    currentEpisode: 8,
    userRating: 91,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(300),
    lastWatchedAt: daysAgo(3),
    nextEpisode: { season: 5, episode: 9, name: "Bad Choice Road", airDate: daysFromNow(1), runtime: 50 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 10, airDate: "2015-02-08" },
      { season: 2, name: "Season 2", episodeCount: 10, airDate: "2016-02-15" },
      { season: 3, name: "Season 3", episodeCount: 10, airDate: "2017-04-10" },
      { season: 4, name: "Season 4", episodeCount: 10, airDate: "2018-08-06" },
      { season: 5, name: "Season 5", episodeCount: 10, airDate: "2020-02-23" },
    ],
    providers: ["Netflix"],
  },
  {
    id: "tv-8",
    tmdbId: 76479,
    mediaType: "tv",
    title: "The Boys",
    posterPath: "/boys.jpg",
    backdropPath: "/boys-bg.jpg",
    overview: "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    releaseDate: "2019-07-25",
    runtime: 60,
    genres: ["Action", "Comedy", "Crime", "Science Fiction"],
    voteAverage: 8.4,
    voteCount: 11234,
    status: "watching",
    progress: 24,
    totalEpisodes: 32,
    currentSeason: 4,
    currentEpisode: 6,
    userRating: 87,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(80),
    lastWatchedAt: daysAgo(2),
    nextEpisode: { season: 4, episode: 7, name: "The Insider", airDate: daysFromNow(2), runtime: 55 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 8, airDate: "2019-07-25" },
      { season: 2, name: "Season 2", episodeCount: 8, airDate: "2020-09-04" },
      { season: 3, name: "Season 3", episodeCount: 8, airDate: "2022-06-03" },
      { season: 4, name: "Season 4", episodeCount: 8, airDate: "2024-06-13" },
    ],
    providers: ["Prime Video"],
  },
  {
    id: "tv-9",
    tmdbId: 94997,
    mediaType: "tv",
    title: "House of the Dragon",
    posterPath: "/hotd.jpg",
    backdropPath: "/hotd-bg.jpg",
    overview: "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke.",
    releaseDate: "2022-08-21",
    runtime: 60,
    genres: ["Drama", "Fantasy", "Action"],
    voteAverage: 8.4,
    voteCount: 7654,
    status: "watching",
    progress: 18,
    totalEpisodes: 18,
    currentSeason: 2,
    currentEpisode: 8,
    userRating: 89,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(60),
    lastWatchedAt: daysAgo(7),
    nextEpisode: { season: 3, episode: 1, name: "TBD", airDate: daysFromNow(120), runtime: 60 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 10, airDate: "2022-08-21" },
      { season: 2, name: "Season 2", episodeCount: 8, airDate: "2024-06-16" },
    ],
    providers: ["HBO Max"],
  },
  {
    id: "tv-10",
    tmdbId: 71912,
    mediaType: "tv",
    title: "The Witcher",
    posterPath: "/witcher.jpg",
    backdropPath: "/witcher-bg.jpg",
    overview: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny.",
    releaseDate: "2019-12-20",
    runtime: 60,
    genres: ["Fantasy", "Action", "Adventure", "Drama"],
    voteAverage: 8.0,
    voteCount: 8765,
    status: "dropped",
    progress: 8,
    totalEpisodes: 24,
    currentSeason: 2,
    currentEpisode: 8,
    userRating: 70,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(250),
    lastWatchedAt: daysAgo(150),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 8, airDate: "2019-12-20" },
      { season: 2, name: "Season 2", episodeCount: 8, airDate: "2021-12-17" },
    ],
    providers: ["Netflix"],
  },
  {
    id: "tv-11",
    tmdbId: 82856,
    mediaType: "tv",
    title: "The Mandalorian",
    posterPath: "/mando.jpg",
    backdropPath: "/mando-bg.jpg",
    overview: "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy.",
    releaseDate: "2019-11-12",
    runtime: 40,
    genres: ["Science Fiction", "Action", "Adventure", "Western"],
    voteAverage: 8.5,
    voteCount: 10234,
    status: "completed",
    progress: 24,
    totalEpisodes: 24,
    currentSeason: 3,
    currentEpisode: 8,
    userRating: 88,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(220),
    lastWatchedAt: daysAgo(40),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 8, airDate: "2019-11-12" },
      { season: 2, name: "Season 2", episodeCount: 8, airDate: "2020-10-30" },
      { season: 3, name: "Season 3", episodeCount: 8, airDate: "2023-03-01" },
    ],
    providers: ["Disney+"],
  },
  {
    id: "tv-12",
    tmdbId: 100088,
    mediaType: "tv",
    title: "The Last of Us",
    posterPath: "/tlou.jpg",
    backdropPath: "/tlou-bg.jpg",
    overview: "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.",
    releaseDate: "2023-01-15",
    runtime: 60,
    genres: ["Drama", "Action", "Adventure", "Science Fiction"],
    voteAverage: 8.7,
    voteCount: 9876,
    status: "completed",
    progress: 9,
    totalEpisodes: 9,
    currentSeason: 1,
    currentEpisode: 9,
    userRating: 94,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(100),
    lastWatchedAt: daysAgo(20),
    nextEpisode: { season: 2, episode: 1, name: "TBD", airDate: daysFromNow(60), runtime: 60 },
    seasons: [{ season: 1, name: "Season 1", episodeCount: 9, airDate: "2023-01-15" }],
    providers: ["HBO Max"],
  },
  {
    id: "tv-13",
    tmdbId: 90802,
    mediaType: "tv",
    title: "The Sandman",
    posterPath: "/sandman.jpg",
    backdropPath: "/sandman-bg.jpg",
    overview: "After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him.",
    releaseDate: "2022-08-05",
    runtime: 50,
    genres: ["Drama", "Fantasy", "Horror", "Mystery"],
    voteAverage: 7.7,
    voteCount: 3234,
    status: "plan_to_watch",
    progress: 0,
    totalEpisodes: 11,
    currentSeason: 1,
    currentEpisode: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(15),
    seasons: [{ season: 1, name: "Season 1", episodeCount: 11, airDate: "2022-08-05" }],
    providers: ["Netflix"],
  },
  {
    id: "tv-14",
    tmdbId: 119051,
    mediaType: "tv",
    title: "Wednesday",
    posterPath: "/wednesday.jpg",
    backdropPath: "/wednesday-bg.jpg",
    overview: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murderous spree while making new friends.",
    releaseDate: "2022-11-23",
    runtime: 50,
    genres: ["Comedy", "Drama", "Fantasy", "Mystery"],
    voteAverage: 8.5,
    voteCount: 8765,
    status: "completed",
    progress: 8,
    totalEpisodes: 8,
    currentSeason: 1,
    currentEpisode: 8,
    userRating: 86,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(80),
    lastWatchedAt: daysAgo(50),
    seasons: [{ season: 1, name: "Season 1", episodeCount: 8, airDate: "2022-11-23" }],
    providers: ["Netflix"],
  },
  {
    id: "tv-15",
    tmdbId: 95479,
    mediaType: "tv",
    title: "Jujutsu Kaisen",
    posterPath: "/jjk.jpg",
    backdropPath: "/jjk-bg.jpg",
    overview: "Yuji Itadori is a boy with tremendous physical strength.",
    releaseDate: "2020-10-03",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Fantasy"],
    voteAverage: 8.7,
    voteCount: 6543,
    status: "watching",
    progress: 47,
    totalEpisodes: 47,
    currentSeason: 2,
    currentEpisode: 22,
    userRating: 95,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(180),
    lastWatchedAt: daysAgo(1),
    nextEpisode: { season: 2, episode: 23, name: "Right and Wrong", airDate: daysFromNow(0), runtime: 24 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 24, airDate: "2020-10-03" },
      { season: 2, name: "Shibuya Incident", episodeCount: 23, airDate: "2023-07-06" },
    ],
    providers: ["Crunchyroll"],
  },
  {
    id: "tv-16",
    tmdbId: 1429,
    mediaType: "tv",
    title: "Attack on Titan",
    posterPath: "/aot.jpg",
    backdropPath: "/aot-bg.jpg",
    overview: "Many years ago, humanity was forced to retreat behind the towering walls of a fortified city.",
    releaseDate: "2013-04-07",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Drama", "Fantasy"],
    voteAverage: 8.6,
    voteCount: 7654,
    status: "completed",
    progress: 89,
    totalEpisodes: 89,
    currentSeason: 4,
    currentEpisode: 28,
    userRating: 97,
    favorite: true,
    rewatchCount: 2,
    addedAt: daysAgo(500),
    lastWatchedAt: daysAgo(25),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 25, airDate: "2013-04-07" },
      { season: 2, name: "Season 2", episodeCount: 12, airDate: "2017-04-01" },
      { season: 3, name: "Season 3", episodeCount: 22, airDate: "2018-07-23" },
      { season: 4, name: "Final Season", episodeCount: 30, airDate: "2020-12-07" },
    ],
    providers: ["Crunchyroll"],
  },
];

// ─────────────────────────────────────────────────────────────
// Movies — 14 items
// ─────────────────────────────────────────────────────────────

const movies: MediaItem[] = [
  {
    id: "mv-1",
    tmdbId: 693134,
    mediaType: "movie",
    title: "Dune: Part Two",
    posterPath: "/dune2.jpg",
    backdropPath: "/dune2-bg.jpg",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen.",
    releaseDate: "2024-03-01",
    runtime: 166,
    genres: ["Science Fiction", "Adventure", "Drama"],
    voteAverage: 8.2,
    voteCount: 6543,
    status: "completed",
    progress: 1,
    userRating: 94,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(60),
    lastWatchedAt: daysAgo(40),
    providers: ["HBO Max", "Netflix"],
  },
  {
    id: "mv-2",
    tmdbId: 533535,
    mediaType: "movie",
    title: "Deadpool & Wolverine",
    posterPath: "/dp-w.jpg",
    backdropPath: "/dp-w-bg.jpg",
    overview: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him.",
    releaseDate: "2024-07-26",
    runtime: 128,
    genres: ["Action", "Adventure", "Comedy", "Science Fiction"],
    voteAverage: 7.7,
    voteCount: 5432,
    status: "completed",
    progress: 1,
    userRating: 88,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(20),
    lastWatchedAt: daysAgo(15),
    providers: ["Disney+"],
  },
  {
    id: "mv-3",
    tmdbId: 823464,
    mediaType: "movie",
    title: "Godzilla x Kong: The New Empire",
    posterPath: "/gxk.jpg",
    backdropPath: "/gxk-bg.jpg",
    overview: "An all-new cinematic adventure, pitting the almighty Kong and the fearsome Godzilla against a colossal undiscovered threat.",
    releaseDate: "2024-03-27",
    runtime: 115,
    genres: ["Action", "Science Fiction", "Adventure"],
    voteAverage: 7.2,
    voteCount: 3456,
    status: "completed",
    progress: 1,
    userRating: 75,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(50),
    lastWatchedAt: daysAgo(45),
    providers: ["HBO Max"],
  },
  {
    id: "mv-4",
    tmdbId: 1022789,
    mediaType: "movie",
    title: "Inside Out 2",
    posterPath: "/io2.jpg",
    backdropPath: "/io2-bg.jpg",
    overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected.",
    releaseDate: "2024-06-14",
    runtime: 96,
    genres: ["Animation", "Family", "Comedy", "Drama"],
    voteAverage: 7.6,
    voteCount: 4321,
    status: "completed",
    progress: 1,
    userRating: 90,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(30),
    lastWatchedAt: daysAgo(10),
    providers: ["Disney+"],
  },
  {
    id: "mv-5",
    tmdbId: 872585,
    mediaType: "movie",
    title: "Oppenheimer",
    posterPath: "/oppen.jpg",
    backdropPath: "/oppen-bg.jpg",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    releaseDate: "2023-07-19",
    runtime: 181,
    genres: ["Drama", "History"],
    voteAverage: 8.1,
    voteCount: 9876,
    status: "completed",
    progress: 1,
    userRating: 95,
    favorite: true,
    rewatchCount: 1,
    addedAt: daysAgo(120),
    lastWatchedAt: daysAgo(35),
    providers: ["Peacock"],
  },
  {
    id: "mv-6",
    tmdbId: 569094,
    mediaType: "movie",
    title: "Spider-Man: Across the Spider-Verse",
    posterPath: "/spider.jpg",
    backdropPath: "/spider-bg.jpg",
    overview: "After reuniting with Gwen Stacy, Miles Morales is catapulted across the Multiverse.",
    releaseDate: "2023-06-02",
    runtime: 140,
    genres: ["Animation", "Action", "Adventure", "Science Fiction"],
    voteAverage: 8.4,
    voteCount: 7654,
    status: "completed",
    progress: 1,
    userRating: 93,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(100),
    lastWatchedAt: daysAgo(28),
    providers: ["Netflix"],
  },
  {
    id: "mv-7",
    tmdbId: 502356,
    mediaType: "movie",
    title: "The Super Mario Bros. Movie",
    posterPath: "/mario.jpg",
    backdropPath: "/mario-bg.jpg",
    overview: "A plumber named Mario travels through an underground labyrinth with his brother.",
    releaseDate: "2023-04-05",
    runtime: 92,
    genres: ["Animation", "Family", "Adventure", "Fantasy", "Comedy"],
    voteAverage: 7.7,
    voteCount: 6543,
    status: "completed",
    progress: 1,
    userRating: 80,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(150),
    lastWatchedAt: daysAgo(80),
    providers: ["Netflix"],
  },
  {
    id: "mv-8",
    tmdbId: 912649,
    mediaType: "movie",
    title: "Venom: The Last Dance",
    posterPath: "/venom3.jpg",
    backdropPath: "/venom3-bg.jpg",
    overview: "Eddie and Venom are on the run from both of their worlds.",
    releaseDate: "2024-10-22",
    runtime: 109,
    genres: ["Action", "Adventure", "Science Fiction"],
    voteAverage: 6.5,
    voteCount: 1234,
    status: "watchlist",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(5),
    providers: ["Netflix"],
  },
  {
    id: "mv-9",
    tmdbId: 558449,
    mediaType: "movie",
    title: "Gladiator II",
    posterPath: "/glad2.jpg",
    backdropPath: "/glad2-bg.jpg",
    overview: "Years after witnessing the death of Maximus, Lucius is forced to enter the Colosseum.",
    releaseDate: "2024-11-22",
    runtime: 148,
    genres: ["Action", "Adventure", "Drama"],
    voteAverage: 6.7,
    voteCount: 987,
    status: "watchlist",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(7),
    providers: ["HBO Max"],
  },
  {
    id: "mv-10",
    tmdbId: 933260,
    mediaType: "movie",
    title: "The Substance",
    posterPath: "/substance.jpg",
    backdropPath: "/substance-bg.jpg",
    overview: "A fading celebrity decides to use a black market drug to create a younger, better version of herself.",
    releaseDate: "2024-09-20",
    runtime: 141,
    genres: ["Horror", "Science Fiction", "Thriller"],
    voteAverage: 7.2,
    voteCount: 1543,
    status: "completed",
    progress: 1,
    userRating: 82,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(25),
    lastWatchedAt: daysAgo(12),
    providers: ["Netflix"],
  },
  {
    id: "mv-11",
    tmdbId: 945961,
    mediaType: "movie",
    title: "Alien: Romulus",
    posterPath: "/alien.jpg",
    backdropPath: "/alien-bg.jpg",
    overview: "Young people from a distant world find themselves in a terrifying encounter with the unknown.",
    releaseDate: "2024-08-13",
    runtime: 119,
    genres: ["Horror", "Science Fiction", "Thriller"],
    voteAverage: 7.0,
    voteCount: 2345,
    status: "completed",
    progress: 1,
    userRating: 78,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(35),
    lastWatchedAt: daysAgo(18),
    providers: ["Hulu"],
  },
  {
    id: "mv-12",
    tmdbId: 912649,
    mediaType: "movie",
    title: "Wicked",
    posterPath: "/wicked.jpg",
    backdropPath: "/wicked-bg.jpg",
    overview: "When two girls meet at university in the Land of Oz, they form an unlikely bond.",
    releaseDate: "2024-11-27",
    runtime: 160,
    genres: ["Fantasy", "Music", "Drama"],
    voteAverage: 7.5,
    voteCount: 1876,
    status: "plan_to_watch",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(3),
    providers: ["Netflix"],
  },
  {
    id: "mv-13",
    tmdbId: 957452,
    mediaType: "movie",
    title: "The Crow",
    posterPath: "/crow.jpg",
    backdropPath: "/crow-bg.jpg",
    overview: "Soulmates Eric and Shelly are brutally murdered. Given a chance to save her, Eric must sacrifice himself.",
    releaseDate: "2024-08-23",
    runtime: 111,
    genres: ["Action", "Crime", "Fantasy", "Horror", "Thriller"],
    voteAverage: 5.7,
    voteCount: 654,
    status: "dropped",
    progress: 0,
    userRating: 40,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(45),
    lastWatchedAt: daysAgo(38),
    providers: ["Netflix"],
  },
  {
    id: "mv-14",
    tmdbId: 1011985,
    mediaType: "movie",
    title: "Kung Fu Panda 4",
    posterPath: "/kfp4.jpg",
    backdropPath: "/kfp4-bg.jpg",
    overview: "Po is getting ready to pass on his Dragon Master title, but a new villain appears.",
    releaseDate: "2024-03-08",
    runtime: 94,
    genres: ["Animation", "Action", "Adventure", "Comedy", "Family"],
    voteAverage: 7.1,
    voteCount: 3210,
    status: "completed",
    progress: 1,
    userRating: 76,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(70),
    lastWatchedAt: daysAgo(55),
    providers: ["Netflix"],
  },
];

// ─────────────────────────────────────────────────────────────
// Anime — 10 items with anime-specific statuses
// ─────────────────────────────────────────────────────────────

const anime: MediaItem[] = [
  {
    id: "an-1",
    tmdbId: 1429,
    mediaType: "anime",
    title: "Attack on Titan",
    posterPath: "/aot-anime.jpg",
    backdropPath: "/aot-anime-bg.jpg",
    overview: "Many years ago, humanity was forced to retreat behind the towering walls of a fortified city.",
    releaseDate: "2013-04-07",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Drama", "Fantasy"],
    voteAverage: 8.6,
    voteCount: 7654,
    status: "completed",
    progress: 89,
    totalEpisodes: 89,
    currentSeason: 4,
    currentEpisode: 28,
    userRating: 97,
    favorite: true,
    rewatchCount: 2,
    addedAt: daysAgo(500),
    lastWatchedAt: daysAgo(25),
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 25, airDate: "2013-04-07" },
      { season: 2, name: "Season 2", episodeCount: 12, airDate: "2017-04-01" },
      { season: 3, name: "Season 3", episodeCount: 22, airDate: "2018-07-23" },
      { season: 4, name: "Final Season", episodeCount: 30, airDate: "2020-12-07" },
    ],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-2",
    tmdbId: 95479,
    mediaType: "anime",
    title: "Jujutsu Kaisen",
    posterPath: "/jjk-anime.jpg",
    backdropPath: "/jjk-anime-bg.jpg",
    overview: "Yuji Itadori is a boy with tremendous physical strength.",
    releaseDate: "2020-10-03",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Fantasy"],
    voteAverage: 8.7,
    voteCount: 6543,
    status: "watching",
    progress: 47,
    totalEpisodes: 47,
    currentSeason: 2,
    currentEpisode: 22,
    userRating: 95,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(180),
    lastWatchedAt: daysAgo(1),
    nextEpisode: { season: 2, episode: 23, name: "Right and Wrong", airDate: daysFromNow(0), runtime: 24 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 24, airDate: "2020-10-03" },
      { season: 2, name: "Shibuya Incident", episodeCount: 23, airDate: "2023-07-06" },
    ],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-3",
    tmdbId: 85937,
    mediaType: "anime",
    title: "Demon Slayer: Kimetsu no Yaiba",
    posterPath: "/ds.jpg",
    backdropPath: "/ds-bg.jpg",
    overview: "Tanjiro Kamado, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon.",
    releaseDate: "2019-04-06",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Fantasy"],
    voteAverage: 8.5,
    voteCount: 8765,
    status: "watching",
    progress: 55,
    totalEpisodes: 63,
    currentSeason: 4,
    currentEpisode: 8,
    userRating: 90,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(220),
    lastWatchedAt: daysAgo(5),
    nextEpisode: { season: 4, episode: 9, name: "TBD", airDate: daysFromNow(7), runtime: 24 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 26, airDate: "2019-04-06" },
      { season: 2, name: "Entertainment District", episodeCount: 18, airDate: "2021-12-05" },
      { season: 3, name: "Swordsmith Village", episodeCount: 11, airDate: "2023-04-09" },
      { season: 4, name: "Hashira Training", episodeCount: 8, airDate: "2024-05-12" },
    ],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-4",
    tmdbId: 95920,
    mediaType: "anime",
    title: "One Piece",
    posterPath: "/op.jpg",
    backdropPath: "/op-bg.jpg",
    overview: "Monkey D. Luffy refuses to let anyone or anything stand in the way of his quest to become the king of all pirates.",
    releaseDate: "1999-10-20",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Comedy", "Fantasy"],
    voteAverage: 8.9,
    voteCount: 11234,
    status: "on_hold",
    progress: 800,
    totalEpisodes: 1100,
    currentSeason: 21,
    currentEpisode: 800,
    userRating: 92,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(700),
    lastWatchedAt: daysAgo(180),
    seasons: [
      { season: 1, name: "East Blue", episodeCount: 61, airDate: "1999-10-20" },
      { season: 2, name: "Entering into the Grand Line", episodeCount: 30, airDate: "2001-03-07" },
    ],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-5",
    tmdbId: 31910,
    mediaType: "anime",
    title: "Naruto Shippuden",
    posterPath: "/naruto.jpg",
    backdropPath: "/naruto-bg.jpg",
    overview: "Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition.",
    releaseDate: "2007-02-15",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure"],
    voteAverage: 8.2,
    voteCount: 6543,
    status: "completed",
    progress: 500,
    totalEpisodes: 500,
    currentSeason: 21,
    currentEpisode: 500,
    userRating: 90,
    favorite: false,
    rewatchCount: 1,
    addedAt: daysAgo(900),
    lastWatchedAt: daysAgo(400),
    seasons: [
      { season: 1, name: "Kazekage Rescue", episodeCount: 32, airDate: "2007-02-15" },
    ],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-6",
    tmdbId: 37854,
    mediaType: "anime",
    title: "One Punch Man",
    posterPath: "/opm.jpg",
    backdropPath: "/opm-bg.jpg",
    overview: "Saitama is a hero who only became a hero for fun.",
    releaseDate: "2015-10-05",
    runtime: 24,
    genres: ["Animation", "Action", "Comedy", "Science Fiction"],
    voteAverage: 8.6,
    voteCount: 5432,
    status: "completed",
    progress: 24,
    totalEpisodes: 24,
    currentSeason: 1,
    currentEpisode: 24,
    userRating: 89,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(300),
    lastWatchedAt: daysAgo(100),
    seasons: [{ season: 1, name: "Season 1", episodeCount: 24, airDate: "2015-10-05" }],
    providers: ["Netflix", "Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-7",
    tmdbId: 65930,
    mediaType: "anime",
    title: "My Hero Academia",
    posterPath: "/mha.jpg",
    backdropPath: "/mha-bg.jpg",
    overview: "In a world where eighty percent of the population has some superpowered Quirk, Izuku was born powerless.",
    releaseDate: "2016-04-03",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Comedy"],
    voteAverage: 8.2,
    voteCount: 6543,
    status: "watching",
    progress: 113,
    totalEpisodes: 138,
    currentSeason: 7,
    currentEpisode: 21,
    userRating: 86,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(280),
    lastWatchedAt: daysAgo(4),
    nextEpisode: { season: 7, episode: 22, name: "TBD", airDate: daysFromNow(4), runtime: 24 },
    seasons: [
      { season: 1, name: "Season 1", episodeCount: 13, airDate: "2016-04-03" },
      { season: 2, name: "Season 2", episodeCount: 25, airDate: "2017-03-25" },
      { season: 3, name: "Season 3", episodeCount: 25, airDate: "2018-04-07" },
      { season: 4, name: "Season 4", episodeCount: 25, airDate: "2019-10-12" },
      { season: 5, name: "Season 5", episodeCount: 25, airDate: "2021-03-27" },
      { season: 6, name: "Season 6", episodeCount: 25, airDate: "2022-10-01" },
      { season: 7, name: "Season 7", episodeCount: 21, airDate: "2024-05-04" },
    ],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-8",
    tmdbId: 114410,
    mediaType: "anime",
    title: "Chainsaw Man",
    posterPath: "/csm.jpg",
    backdropPath: "/csm-bg.jpg",
    overview: "Denji has a simple dream—to live a happy and peaceful life with the girl he likes.",
    releaseDate: "2022-10-11",
    runtime: 24,
    genres: ["Animation", "Action", "Adventure", "Horror", "Science Fiction"],
    voteAverage: 8.4,
    voteCount: 4321,
    status: "completed",
    progress: 12,
    totalEpisodes: 12,
    currentSeason: 1,
    currentEpisode: 12,
    userRating: 91,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(90),
    lastWatchedAt: daysAgo(15),
    seasons: [{ season: 1, name: "Season 1", episodeCount: 12, airDate: "2022-10-11" }],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-9",
    tmdbId: 125996,
    mediaType: "anime",
    title: "Frieren: Beyond Journey's End",
    posterPath: "/frieren.jpg",
    backdropPath: "/frieren-bg.jpg",
    overview: "The mage Frieren learns more about people in the years after defeating the Demon King.",
    releaseDate: "2023-09-29",
    runtime: 24,
    genres: ["Animation", "Adventure", "Drama", "Fantasy"],
    voteAverage: 8.9,
    voteCount: 2345,
    status: "watching",
    progress: 24,
    totalEpisodes: 28,
    currentSeason: 1,
    currentEpisode: 24,
    userRating: 96,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(60),
    lastWatchedAt: daysAgo(2),
    nextEpisode: { season: 1, episode: 25, name: "TBD", airDate: daysFromNow(1), runtime: 24 },
    seasons: [{ season: 1, name: "Season 1", episodeCount: 28, airDate: "2023-09-29" }],
    providers: ["Crunchyroll"],
    originalLanguage: "ja",
  },
  {
    id: "an-10",
    tmdbId: 21024,
    mediaType: "anime",
    title: "Death Note",
    posterPath: "/dn.jpg",
    backdropPath: "/dn-bg.jpg",
    overview: "Light Yagami is a genius high school student who discovers a supernatural notebook.",
    releaseDate: "2006-10-04",
    runtime: 24,
    genres: ["Animation", "Crime", "Drama", "Mystery", "Thriller"],
    voteAverage: 8.6,
    voteCount: 9876,
    status: "completed",
    progress: 37,
    totalEpisodes: 37,
    currentSeason: 1,
    currentEpisode: 37,
    userRating: 93,
    favorite: false,
    rewatchCount: 1,
    addedAt: daysAgo(700),
    lastWatchedAt: daysAgo(500),
    seasons: [{ season: 1, name: "Season 1", episodeCount: 37, airDate: "2006-10-04" }],
    providers: ["Netflix"],
    originalLanguage: "ja",
  },
];

// ─────────────────────────────────────────────────────────────
// Arabic TV — 10 items
// ─────────────────────────────────────────────────────────────

const arabicTV: MediaItem[] = [
  {
    id: "atv-1",
    tmdbId: 100001,
    mediaType: "arabic_tv",
    title: "العهد",
    posterPath: "/ahd.jpg",
    backdropPath: "/ahd-bg.jpg",
    overview: "دراما تاريخية تدور أحداثها في عالم مليء بالأسرار والصراعات.",
    releaseDate: "2024-03-15",
    runtime: 45,
    genres: ["تاريخي", "دراما", "تشويق"],
    voteAverage: 8.4,
    voteCount: 1234,
    status: "watching",
    progress: 25,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 25,
    userRating: 88,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(120),
    lastWatchedAt: hoursAgo(12),
    nextEpisode: { season: 1, episode: 26, name: "الحلقة 26", airDate: daysFromNow(1), runtime: 45 },
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-03-15" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "atv-2",
    tmdbId: 100002,
    mediaType: "arabic_tv",
    title: "جعفر العمدة",
    posterPath: "/jaafar.jpg",
    backdropPath: "/jaafar-bg.jpg",
    overview: "مسلسل كوميدي اجتماعي يحكي قصة رجل أعمال ناجح يواجه مواقف طريفة.",
    releaseDate: "2024-04-01",
    runtime: 45,
    genres: ["كوميديا", "اجتماعي"],
    voteAverage: 7.8,
    voteCount: 987,
    status: "watching",
    progress: 18,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 18,
    userRating: 80,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(60),
    lastWatchedAt: daysAgo(3),
    nextEpisode: { season: 1, episode: 19, name: "الحلقة 19", airDate: daysFromNow(2), runtime: 45 },
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-04-01" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "atv-3",
    tmdbId: 100003,
    mediaType: "arabic_tv",
    title: "كبير آه",
    posterPath: "/kabir.jpg",
    backdropPath: "/kabir-bg.jpg",
    overview: "دراما مصرية تدور حول صراع العائلات والعادات والتقاليد.",
    releaseDate: "2023-09-20",
    runtime: 45,
    genres: ["دراما", "تشويق"],
    voteAverage: 8.0,
    voteCount: 765,
    status: "completed",
    progress: 30,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 30,
    userRating: 82,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(150),
    lastWatchedAt: daysAgo(40),
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2023-09-20" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "atv-4",
    tmdbId: 100004,
    mediaType: "arabic_tv",
    title: "ضرب نار",
    posterPath: "/darb.jpg",
    backdropPath: "/darb-bg.jpg",
    overview: "مسلسل بوليسي مصري عن ضابط يطارد عصابة خطيرة.",
    releaseDate: "2024-05-10",
    runtime: 45,
    genres: ["بوليسي", "تشويق", "دراما"],
    voteAverage: 8.2,
    voteCount: 654,
    status: "watching",
    progress: 20,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 20,
    userRating: 85,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(70),
    lastWatchedAt: daysAgo(2),
    nextEpisode: { season: 1, episode: 21, name: "الحلقة 21", airDate: daysFromNow(0), runtime: 45 },
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-05-10" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "atv-5",
    tmdbId: 100005,
    mediaType: "arabic_tv",
    title: "الحشاشين",
    posterPath: "/hashasheen.jpg",
    backdropPath: "/hashasheen-bg.jpg",
    overview: "مسلسل تاريخي يحكي قصة فرقة الحشاشين بقيادة الحسن الصباح.",
    releaseDate: "2024-03-25",
    runtime: 45,
    genres: ["تاريخي", "دراما", "تشويق"],
    voteAverage: 8.5,
    voteCount: 1543,
    status: "completed",
    progress: 30,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 30,
    userRating: 90,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(90),
    lastWatchedAt: daysAgo(20),
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-03-25" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "atv-6",
    tmdbId: 100006,
    mediaType: "arabic_tv",
    title: "نسب عريق",
    posterPath: "/nasab.jpg",
    backdropPath: "/nasab-bg.jpg",
    overview: "دراما خليجية عن العائلة والتراث والصراعات العائلية.",
    releaseDate: "2024-02-01",
    runtime: 45,
    genres: ["دراما", "اجتماعي"],
    voteAverage: 7.5,
    voteCount: 432,
    status: "on_hold",
    progress: 15,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 15,
    userRating: 70,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(100),
    lastWatchedAt: daysAgo(50),
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-02-01" }],
    providers: ["Shahid"],
    country: "SA",
    originalLanguage: "ar",
  },
  {
    id: "atv-7",
    tmdbId: 100007,
    mediaType: "arabic_tv",
    title: "بيت الرفاعي",
    posterPath: "/rifai.jpg",
    backdropPath: "/rifai-bg.jpg",
    overview: "دراما مصرية تدور حول عائلة الرفاعي وأسرارها المتعددة.",
    releaseDate: "2024-06-01",
    runtime: 45,
    genres: ["دراما", "تشويق"],
    voteAverage: 7.9,
    voteCount: 543,
    status: "watchlist",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(7),
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-06-01" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "atv-8",
    tmdbId: 100008,
    mediaType: "arabic_tv",
    title: "ملك الفلامنكو",
    posterPath: "/flamenco.jpg",
    backdropPath: "/flamenco-bg.jpg",
    overview: "كوميديا مصرية عن موسيقي يطمح للشهرة العالمية.",
    releaseDate: "2024-04-15",
    runtime: 45,
    genres: ["كوميديا", "رومانسي"],
    voteAverage: 7.0,
    voteCount: 234,
    status: "completed",
    progress: 30,
    totalEpisodes: 30,
    currentSeason: 1,
    currentEpisode: 30,
    userRating: 72,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(85),
    lastWatchedAt: daysAgo(45),
    seasons: [{ season: 1, name: "الموسم الأول", episodeCount: 30, airDate: "2024-04-15" }],
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
];

// ─────────────────────────────────────────────────────────────
// Arabic Movies — 10 items
// ─────────────────────────────────────────────────────────────

const arabicMovies: MediaItem[] = [
  {
    id: "amv-1",
    tmdbId: 200001,
    mediaType: "arabic_movie",
    title: "وش في وش",
    posterPath: "/wesh.jpg",
    backdropPath: "/wesh-bg.jpg",
    overview: "كوميديا مصرية عن صديقين يكتشفان أسرارًا عن بعضهما البعض.",
    releaseDate: "2024-06-15",
    runtime: 110,
    genres: ["كوميديا", "رومانسي"],
    voteAverage: 7.2,
    voteCount: 432,
    status: "completed",
    progress: 1,
    userRating: 78,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(30),
    lastWatchedAt: daysAgo(18),
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "amv-2",
    tmdbId: 200002,
    mediaType: "arabic_movie",
    title: "العميل صفر",
    posterPath: "/agent.jpg",
    backdropPath: "/agent-bg.jpg",
    overview: "أكشن مصري عن عميل سري يطارد إرهابيًا خطيرًا.",
    releaseDate: "2024-05-01",
    runtime: 120,
    genres: ["Action", "تشويق", "بوليسي"],
    voteAverage: 7.8,
    voteCount: 543,
    status: "completed",
    progress: 1,
    userRating: 82,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(50),
    lastWatchedAt: daysAgo(35),
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "amv-3",
    tmdbId: 200003,
    mediaType: "arabic_movie",
    title: "أبو نسب",
    posterPath: "/abunasab.jpg",
    backdropPath: "/abunasab-bg.jpg",
    overview: "كوميديا اجتماعية عن رجل يكتشف أن له عائلة موسعة.",
    releaseDate: "2024-07-01",
    runtime: 105,
    genres: ["كوميديا", "اجتماعي", "دراما"],
    voteAverage: 7.5,
    voteCount: 321,
    status: "completed",
    progress: 1,
    userRating: 80,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(20),
    lastWatchedAt: daysAgo(8),
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "amv-4",
    tmdbId: 200004,
    mediaType: "arabic_movie",
    title: "تالت جمعة",
    posterPath: "/talatgouma.jpg",
    backdropPath: "/talatgouma-bg.jpg",
    overview: "دراما عن عائلة مصرية تواجه تحديات الحياة اليومية.",
    releaseDate: "2024-04-20",
    runtime: 115,
    genres: ["دراما", "اجتماعي"],
    voteAverage: 7.0,
    voteCount: 234,
    status: "watchlist",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(5),
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "amv-5",
    tmdbId: 200005,
    mediaType: "arabic_movie",
    title: "السرب",
    posterPath: "/squad.jpg",
    backdropPath: "/squad-bg.jpg",
    overview: "أكشن مصري عن فريق إنقاذ يواجه منظمة إجرامية.",
    releaseDate: "2024-08-10",
    runtime: 125,
    genres: ["Action", "تشويق", "بوليسي"],
    voteAverage: 7.3,
    voteCount: 187,
    status: "watchlist",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(3),
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "amv-6",
    tmdbId: 200006,
    mediaType: "arabic_movie",
    title: "الست لما",
    posterPath: "/lama.jpg",
    backdropPath: "/lama-bg.jpg",
    overview: "دراما تاريخية عن سيدة مصرية شهيرة في الخمسينيات.",
    releaseDate: "2024-03-01",
    runtime: 130,
    genres: ["تاريخي", "دراما", "رومانسي"],
    voteAverage: 8.0,
    voteCount: 654,
    status: "completed",
    progress: 1,
    userRating: 86,
    favorite: true,
    rewatchCount: 0,
    addedAt: daysAgo(75),
    lastWatchedAt: daysAgo(42),
    providers: ["Shahid"],
    country: "EG",
    originalLanguage: "ar",
  },
  {
    id: "amv-7",
    tmdbId: 200007,
    mediaType: "arabic_movie",
    title: "حامل اللواء",
    posterPath: "/haml.jpg",
    backdropPath: "/haml-bg.jpg",
    overview: "كوميديا سعودية عن رجل يحاول إنقاذ بلدته.",
    releaseDate: "2024-09-01",
    runtime: 100,
    genres: ["كوميديا", "اجتماعي"],
    voteAverage: 6.8,
    voteCount: 154,
    status: "plan_to_watch",
    progress: 0,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(2),
    providers: ["Shahid"],
    country: "SA",
    originalLanguage: "ar",
  },
  {
    id: "amv-8",
    tmdbId: 200008,
    mediaType: "arabic_movie",
    title: "العاشق",
    posterPath: "/asheq.jpg",
    backdropPath: "/asheq-bg.jpg",
    overview: "رومانسية درامية عن حب مستحيل في زمن الحرب.",
    releaseDate: "2024-02-15",
    runtime: 118,
    genres: ["رومانسي", "دراما", "تاريخي"],
    voteAverage: 7.4,
    voteCount: 376,
    status: "completed",
    progress: 1,
    userRating: 79,
    favorite: false,
    rewatchCount: 0,
    addedAt: daysAgo(90),
    lastWatchedAt: daysAgo(55),
    providers: ["Shahid"],
    country: "LB",
    originalLanguage: "ar",
  },
];

// ─────────────────────────────────────────────────────────────
// Combine and re-export
// ─────────────────────────────────────────────────────────────

export const allMedia: MediaItem[] = [
  ...tvShows,
  ...movies,
  ...anime,
  ...arabicTV,
  ...arabicMovies,
];

export const getMediaByType = (type: MediaType): MediaItem[] =>
  allMedia.filter((m) => m.mediaType === type);

export const getMediaByStatus = (type: MediaType, status: string): MediaItem[] =>
  allMedia.filter((m) => m.mediaType === type && m.status === status);

// ─────────────────────────────────────────────────────────────
// Calendar entries — built from upcoming episodes
// ─────────────────────────────────────────────────────────────

export const calendarEntries: CalendarEntry[] = allMedia
  .filter((m) => m.nextEpisode && (m.mediaType === "tv" || m.mediaType === "anime" || m.mediaType === "arabic_tv"))
  .map((m) => ({
    date: m.nextEpisode!.airDate,
    mediaType: m.mediaType,
    tmdbId: m.tmdbId,
    title: m.title,
    posterPath: m.posterPath,
    season: m.nextEpisode!.season,
    episode: m.nextEpisode!.episode,
    name: m.nextEpisode!.name,
    runtime: m.nextEpisode!.runtime,
    watched: false,
  }));

// Upcoming movie releases
export const upcomingMovieReleases = allMedia
  .filter((m) => (m.mediaType === "movie" || m.mediaType === "arabic_movie") && m.releaseDate)
  .map((m) => ({
    date: m.releaseDate!,
    mediaType: m.mediaType,
    tmdbId: m.tmdbId,
    title: m.title,
    posterPath: m.posterPath,
    season: 0,
    episode: 0,
    name: m.title,
    runtime: m.runtime,
    watched: m.status === "completed",
  }));

// ─────────────────────────────────────────────────────────────
// Watch sessions — for statistics (deep personal analysis)
// ─────────────────────────────────────────────────────────────

const sessions: WatchSession[] = [];
let sessionCounter = 0;

const generateSessions = () => {
  // Generate ~6 months of watch sessions
  for (let dayOffset = 0; dayOffset < 180; dayOffset++) {
    const date = new Date(today);
    date.setDate(date.getDate() - dayOffset);
    const dateStr = date.toISOString();
    const dayOfWeek = date.getDay(); // 0 = Sunday

    // Watch activity varies by day of week
    const baseActivity = [0.4, 0.3, 0.5, 0.4, 0.7, 1.0, 0.9][dayOfWeek];
    if (Math.random() > baseActivity) continue;

    // Sessions per day (1-4)
    const sessionCount = Math.floor(Math.random() * 4 * baseActivity) + 1;
    for (let i = 0; i < sessionCount; i++) {
      const pool = allMedia.filter((m) => m.status === "watching" || m.status === "completed");
      const media = pool[Math.floor(Math.random() * pool.length)];
      const hour = [19, 20, 21, 22, 23, 0, 1][Math.floor(Math.random() * 7)] + Math.floor(Math.random() * 2);

      sessions.push({
        id: `s-${sessionCounter++}`,
        mediaType: media.mediaType,
        tmdbId: media.tmdbId,
        title: media.title,
        season: media.currentSeason,
        episode: (media.currentEpisode || 0) - i,
        watchedAt: dateStr,
        duration: media.runtime || 45,
        rewatch: Math.random() < 0.05,
        rating: media.userRating,
        source: media.providers?.[0] || "Unknown",
      });
    }
  }
};
generateSessions();

export const watchSessions = sessions;

// ─────────────────────────────────────────────────────────────
// Notifications
// ─────────────────────────────────────────────────────────────

export const notifications: Notification[] = [
  {
    id: "n-1",
    type: "new_episode",
    title: "حلقة جديدة: Jujutsu Kaisen",
    body: "الموسم 2 الحلقة 23 صدرت الآن. شاهدْها!",
    tmdbId: 95479,
    mediaType: "anime",
    read: false,
    createdAt: hoursAgo(2),
  },
  {
    id: "n-2",
    type: "new_episode",
    title: "حلقة جديدة: ضرب نار",
    body: "الحلقة 21 من المسلسل صدرت اليوم.",
    tmdbId: 100004,
    mediaType: "arabic_tv",
    read: false,
    createdAt: hoursAgo(5),
  },
  {
    id: "n-3",
    type: "backlog_alert",
    title: "لديك 5 حلقات متراكمة",
    body: "لم تشاهد 5 حلقات من المسلسلات التي تتابعها.",
    read: false,
    createdAt: hoursAgo(24),
  },
  {
    id: "n-4",
    type: "season_return",
    title: "عودة موسم: The Last of Us",
    body: "الموسم الثاني سيبدأ خلال 60 يومًا.",
    tmdbId: 100088,
    mediaType: "tv",
    read: true,
    createdAt: daysAgo(3),
  },
];

// ─────────────────────────────────────────────────────────────
// Custom Lists (kept minimal — not the focus per user request)
// ─────────────────────────────────────────────────────────────

export const customLists: CustomList[] = [
  {
    id: "cl-1",
    name: "أفضل أفلام 2024",
    description: "أفلام هذا العام التي أعجبتني",
    isPublic: false,
    color: "#f59e0b",
    items: [
      { tmdbId: 693134, mediaType: "movie", title: "Dune: Part Two", addedAt: daysAgo(60) },
      { tmdbId: 872585, mediaType: "movie", title: "Oppenheimer", addedAt: daysAgo(120) },
      { tmdbId: 569094, mediaType: "movie", title: "Spider-Man: Across the Spider-Verse", addedAt: daysAgo(100) },
    ],
    createdAt: daysAgo(60),
  },
];

// ─────────────────────────────────────────────────────────────
// TMDB Discover mock — for the Discover sections
// ─────────────────────────────────────────────────────────────

export const discoverTrending: MediaItem[] = [
  ...allMedia.filter((m) => (m.voteAverage || 0) >= 8.0).slice(0, 12),
];

export const discoverMovies: MediaItem[] = allMedia.filter((m) => m.mediaType === "movie");
export const discoverTV: MediaItem[] = allMedia.filter((m) => m.mediaType === "tv");
export const discoverAnime: MediaItem[] = allMedia.filter((m) => m.mediaType === "anime");
export const discoverArabicMovies: MediaItem[] = allMedia.filter((m) => m.mediaType === "arabic_movie");
export const discoverArabicTV: MediaItem[] = allMedia.filter((m) => m.mediaType === "arabic_tv");

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

export const getAllGenres = (type?: MediaType): string[] => {
  const items = type ? allMedia.filter((m) => m.mediaType === type) : allMedia;
  const set = new Set<string>();
  items.forEach((m) => m.genres.forEach((g) => set.add(g)));
  return Array.from(set).sort();
};

export const pickGradientForMedia = (m: MediaItem): string => {
  return pickGradient(m.tmdbId);
};

export { pickGradient };
